import {missions,completed,score} from './missions.js';
import {showQuiz} from './quiz.js';
export const $=s=>document.querySelector(s);
export const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class UI{
constructor(getState,save,hooks){this.getState=getState;this.save=save;this.hooks=hooks;this.opened=false;$('#closeModal').onclick=()=>this.close();$('#missionBtn').onclick=()=>this.missionPanel();$('#helpBtn').onclick=()=>this.help();$('#reflectionBtn').onclick=()=>this.reflections();$('#mapBtn').onclick=()=>{$('#mapBox').hidden=!$('#mapBox').hidden;$('#mapBtn').setAttribute('aria-expanded',String(!$('#mapBox').hidden));};$('#soundBtn').onclick=()=>{const s=getState();s.sound=!s.sound;save();this.update();hooks.sound('open');};document.addEventListener('keydown',e=>{if(!this.opened)return;if(e.key==='Escape'){this.close();return;}if(e.key==='Tab'){const nodes=[...$('.panel').querySelectorAll('button,input,textarea')].filter(n=>!n.disabled&&n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('.panel'))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});}
show(html){if(!this.opened)this.previousFocus=document.activeElement;this.opened=true;this.hooks.pause();$('#modal').hidden=false;$('#dialogContent').innerHTML=html;$('.panel').scrollTop=0;$('.panel').focus();for(const id of ['hud','controls','start'])$('#'+id).inert=true;}
close(){this.opened=false;$('#modal').hidden=true;for(const id of ['hud','controls','start'])$('#'+id).inert=false;this.hooks.resume();if(this.previousFocus?.getClientRects().length)this.previousFocus.focus();else $('#world').focus();}
button(id,fn){$('#'+id).onclick=fn;}
update(){const s=this.getState();$('#score').textContent=`⭐ ${score(s)} / 100`;$('#count').textContent=`🎯 ${completed(s)} / 5`;$('#soundBtn').textContent=s.sound?'🔊 Bunyi':'🔇 Bunyi';$('#soundBtn').setAttribute('aria-pressed',String(s.sound));$('#objective strong').textContent=completed(s)===5?(s.finished?'Kamu Juara Kesederhanaan!':'Kembali ke Dewan Komuniti.'):'Lima misi, pilihan sederhana.';$('#objective span').textContent=completed(s)===5?'Temui Kumar di hadapan dewan.':'Ikuti jalan dan cari penduduk bertanda ❗';$('#missionList').innerHTML=missions.map(m=>`<div>${Object.hasOwn(s.done,m.id)?'✅':'☐'} ${m.place}</div>`).join('');}
help(){this.show('<span class="tag">JELAJAH • FIKIR • AMALKAN</span><h2 id="dialogTitle">🎮 Cara bermain</h2><p><b>W / ↑:</b> maju · <b>S / ↓:</b> undur<br><b>A / ←:</b> kiri · <b>D / →:</b> kanan<br><b>Shift:</b> berlari perlahan<br><b>Seret pada dunia:</b> putar kamera<br><b>E / 💬 BERCAKAP:</b> berinteraksi apabila dekat.</p><p>Pada telefon atau tablet, gerakkan <b>joystick di kiri</b>. Seret bahagian kanan dunia untuk melihat sekeliling. Gerakan mengikut arah kamera.</p><p>Cari lima NPC bertanda ❗. Baca dilema, pilih jawapan, kemudian nyatakan perasaan. Kamu boleh mencuba lagi tanpa kehilangan mata. Selepas lima misi, kembali ke Dewan Komuniti dan bercakap dengan Kumar.</p><button class="primary" id="understood">Faham, jom main!</button>');this.button('understood',()=>this.close());}
mission(m){const s=this.getState();if(m.id==='kumar'&&completed(s)===5){s.finished=true;this.save();this.update();this.hooks.finish();return this.victory();}if(Object.hasOwn(s.done,m.id)){this.show(`<span class="tag">${m.place}</span><h2 id="dialogTitle">✅ ${m.npc}</h2><p>${m.feedback}</p><p>Misi ini sudah selesai. Mata kamu telah disimpan.</p><button class="primary" id="doneTalk">Teruskan pengembaraan</button>`);return this.button('doneTalk',()=>this.close());}showQuiz(this,m);}
missionPanel(){const s=this.getState();this.show(`<span class="tag">CATATAN PENGEMBARAAN</span><h2 id="dialogTitle">📋 MISI KAMPUNG</h2>${missions.map(m=>`<div class="missionRow"><div><b>${Object.hasOwn(s.done,m.id)?'✅':'☐'} ${m.icon} ${m.place}</b><small>${m.npc} · ${m.topic}</small></div><span>${Object.hasOwn(s.done,m.id)?m.points+' mata':'Belum selesai'}</span></div>`).join('')}<p>⭐ ${score(s)} / 100 Mata Kesederhanaan</p><div class="actions"><button id="viewReflection">📋 Lihat refleksi saya</button><button id="restartBtn">🔄 Main semula</button><button id="resetBtn">Padam kemajuan</button></div>`);this.button('viewReflection',()=>this.reflections());this.button('restartBtn',()=>this.reset());this.button('resetBtn',()=>this.reset());}
reset(){this.show('<h2 id="dialogTitle">🔄 Main semula?</h2><p>Semua mata, misi dan refleksi pada pelayar ini akan dipadam. Pemain akan kembali ke rumah.</p><div class="actions"><button id="cancelReset">Kembali</button><button class="primary" id="confirmReset">Ya, padam kemajuan</button></div>');this.button('cancelReset',()=>this.missionPanel());this.button('confirmReset',()=>{this.close();this.hooks.reset();});}
reflections(){const s=this.getState();this.show(`<span class="tag">PERASAAN & PEMBELAJARAN</span><h2 id="dialogTitle">📋 Refleksi saya</h2><p>${escapeHTML(s.name||'Pengembara')} · ⭐ ${score(s)} / 100</p>${missions.map(m=>`<article class="reflection"><h3>${m.icon} ${m.place}</h3><p>${escapeHTML(s.feelings[m.id]||'Belum melengkapkan refleksi.')}</p>${Object.hasOwn(s.done,m.id)?`<small>${m.feedback}</small>`:''}</article>`).join('')}<button class="primary" id="backWorld">Kembali ke kampung</button>`);this.button('backWorld',()=>this.close());}
victory(){this.hooks.sound('win');this.confetti();this.show(`<span class="tag">PENGEMBARAAN SELESAI</span><h2 id="dialogTitle">🎉 TAHNIAH!</h2><p><b>ANDA BERJAYA MENYELESAIKAN MISI KAMPUNG SEDERHANA!</b></p><div class="feedback">⭐ ${score(this.getState())} / 100 Mata Kesederhanaan</div><ul class="summary">${missions.map(m=>`<li>${m.icon} ${m.summary}</li>`).join('')}</ul><p>“Kesederhanaan membantu kita menjalani kehidupan yang seimbang, menghormati orang lain dan mengelakkan pembaziran.”</p><div class="actions"><button class="primary" id="viewReflection">📋 Lihat refleksi saya</button><button id="restartBtn">🔄 Main semula</button><button id="exploreMore">Lihat penduduk</button></div>`);this.button('viewReflection',()=>this.reflections());this.button('restartBtn',()=>this.reset());this.button('exploreMore',()=>this.close());}
confetti(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<28;i++){const e=document.createElement('i');e.className='confetti';e.textContent='★';e.style.left=Math.random()*100+'%';e.style.color=['#ffd166','#ef476f','#06d6a0','#4ea8de'][i%4];e.style.animationDelay=Math.random()*.4+'s';$('#confetti').append(e);setTimeout(()=>e.remove(),3500);}}
}
