import * as THREE from './assets/vendor/three.module.js';
import {character,animateCharacter} from './js/player.js';
import {createWorld} from './js/world.js';
import {missions,fresh,readState,saveState,completed} from './js/missions.js';
import {UI,$} from './js/ui.js';
import {joystick} from './js/controls.js';
import {createNPCs,gatherNPCs} from './js/npc.js';
const stick=joystick();
const canvas=$('#world');
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();document.querySelector('#toast').hidden=false;document.querySelector('#toast').textContent='Paparan 3D terhenti. Muat semula halaman untuk menyambung kemajuan terakhir.';});
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xbfe5f5);scene.fog=new THREE.Fog(0xbfe5f5,48,105);scene.add(new THREE.AmbientLight(0xffffff,1.8));const sun=new THREE.DirectionalLight(0xfff0d3,2.3);sun.position.set(-25,40,20);scene.add(sun);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,160);const world=createWorld(scene);const player=character({shirt:0x4ea8de});scene.add(player);
const labelEntries=[];function addLabel(text,position,type=''){const el=document.createElement('div');el.className='world-label '+type;el.textContent=text;$('#labels').append(el);const item={el,position};labelEntries.push(item);return item;}
world.labels.forEach(l=>addLabel(l.text,l.position));const npcs=createNPCs(scene,missions,addLabel);
let state=readState()||fresh(),started=false,yaw=0,pitch=.58,near=null,talking=null,celebrating=false,lastSave=0,lastFoot=0;const keys=new Set();const clock=new THREE.Clock();let elapsed=0,drag=null,audio=null,toastTimer,storageWarning=false;
function sound(kind){if(!state.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const now=audio.currentTime;const notes={open:[440],wrong:[180],correct:[523,659],complete:[523,659,784],win:[523,659,784,1047],step:[95]}[kind]||[440];notes.forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type=kind==='step'?'sine':'triangle';o.frequency.value=f;g.gain.setValueAtTime(0,now+i*.12);g.gain.linearRampToValueAtTime(kind==='step'?.025:.065,now+i*.12+.01);g.gain.exponentialRampToValueAtTime(.001,now+i*.12+.13);o.connect(g);g.connect(audio.destination);o.start(now+i*.12);o.stop(now+i*.12+.15);});}catch{}}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4000);}
function save(){state.position={x:player.position.x,z:player.position.z};if(!saveState(state)&&!storageWarning){storageWarning=true;toast('Kemajuan tidak dapat disimpan pada pelayar ini. Teruskan sesi tanpa menutup halaman.');}}
function celebration(){celebrating=true;gatherNPCs(npcs);yaw=0;pitch=.58;save();}
function restoreNPCs(){celebrating=false;npcs.forEach(n=>{n.model.position.set(n.mission.x,0,n.mission.z);n.model.userData.limbs.forEach(l=>l.rotation.set(0,0,0));});}
const ui=new UI(()=>state,save,{sound,pause(){keys.clear();stick.clear();drag=null;},resume(){talking=null;keys.clear();stick.clear();},completed(){updateLabels();if(completed(state)===5)gatherNPCs(npcs);ui.confetti();},finish:celebration,reset(){restoreNPCs();state=fresh();started=false;keys.clear();$('#start').hidden=false;$('#playerName').value='';$('#continueBtn').hidden=true;$('#startBtn').textContent='🎮 MULAKAN MISI';['hud','mapBox','objective','controls','desktopHint','prompt'].forEach(id=>$('#'+id).hidden=true);player.position.set(-24,0,6);saveState(state);}});
function updateLabels(){for(const n of npcs){const done=Object.hasOwn(state.done,n.mission.id);n.label.el.textContent=(done?'✅ ':'❗ ')+n.mission.name;}}
function isBlocked(x,z){if(x<-36||x>36||z<-35||z>55)return true;const r=.32;const box=new THREE.Box3(new THREE.Vector3(x-r,.05,z-r),new THREE.Vector3(x+r,2.2,z+r));if(world.solids.some(b=>box.intersectsBox(b)))return true;return npcs.some(n=>Math.abs(x-n.model.position.x)<.7&&Math.abs(z-n.model.position.z)<.7);}
function start(resume){restoreNPCs();if(!resume){state=fresh();state.name=$('#playerName').value.trim()||'Pengembara';}started=true;$('#start').hidden=true;['hud','mapBox','objective','controls','desktopHint'].forEach(id=>$('#'+id).hidden=false);player.position.set(state.position.x,0,state.position.z);if(isBlocked(player.position.x,player.position.z))player.position.set(-24,0,6);yaw=-Math.PI/2;player.rotation.y=Math.PI/2;camera.position.copy(player.position).add(new THREE.Vector3(-11,7.5,0));ui.update();updateLabels();save();if(completed(state)===5){gatherNPCs(npcs);if(state.finished)toast('Selamat kembali, Juara Kesederhanaan! Buka Refleksi untuk melihat catatan kamu.');}else if(!resume)ui.help();}
$('#startBtn').disabled=false;$('#startBtn').textContent='🎮 MULAKAN MISI';$('#loadStatus').textContent='Dunia sudah bersedia. Jom teroka!';$('#playerName').value=state.name;if(state.name){$('#continueBtn').hidden=false;$('#startBtn').textContent='Pengembaraan baharu';}
$('#startBtn').onclick=()=>{if(state.name){ui.show('<h2 id="dialogTitle">Pengembaraan baharu?</h2><p>Ini akan menggantikan kemajuan yang disimpan pada pelayar ini.</p><div class="actions"><button id="keep">Kembali</button><button class="primary" id="new">Ya, mulakan</button></div>');$('#keep').onclick=()=>ui.close();$('#new').onclick=()=>{ui.close();start(false);};}else start(false);};$('#continueBtn').onclick=()=>start(true);
function interact(){if(!started||ui.opened||!near)return;talking=near;player.rotation.y=Math.atan2(near.model.position.x-player.position.x,near.model.position.z-player.position.z);near.model.rotation.y=Math.atan2(player.position.x-near.model.position.x,player.position.z-near.model.position.z);ui.mission(near.mission);}
$('#interact').onclick=interact;
const movementKeys=['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Shift'];window.addEventListener('keydown',e=>{if(!started||ui.opened||['INPUT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(movementKeys.includes(k)){e.preventDefault();keys.add(k);}if(k==='e'&&!e.repeat)interact();});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{keys.clear();drag=null;if(started)save();});document.addEventListener('visibilitychange',()=>{keys.clear();if(started)save();});window.addEventListener('pagehide',()=>{if(started)save();});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{if(ui.opened||!started)return;e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.key));}
canvas.addEventListener('pointerdown',e=>{if(!started||ui.opened)return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;yaw-=(e.clientX-drag.x)*.006;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-drag.y)*.003,.36,.9);drag.x=e.clientX;drag.y=e.clientY;});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>drag=null);
window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
const map=$('#map'),ctx=map.getContext('2d');const mx=x=>150+x*3,mz=z=>24+(z+35)*2.5;
function drawMap(){ctx.clearRect(0,0,300,280);ctx.fillStyle='#e4edda';ctx.fillRect(0,0,300,280);ctx.strokeStyle='#cbbc97';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(mx(-24),mz(4));ctx.lineTo(mx(24),mz(4));ctx.moveTo(mx(0),mz(-29));ctx.lineTo(mx(0),mz(46));ctx.stroke();ctx.font='12px Arial';ctx.textAlign='center';for(const m of missions){const done=Object.hasOwn(state.done,m.id);ctx.fillStyle='#36594b';ctx.fillText(m.icon+' '+(done?'✅':'❗'),mx(m.x),mz(m.z));ctx.font='10px Arial';ctx.fillText({mei:'Pasar raya',kumar:'Dewan',teck:'Internet',aisyah:'Rumah terbuka',ravi:'Taman'}[m.id],mx(m.x),mz(m.z)+13);ctx.font='12px Arial';}ctx.fillText('🏠',mx(-24),mz(4));ctx.font='10px Arial';ctx.fillText('Rumah',mx(-24),mz(4)+13);ctx.fillStyle='#2786cf';ctx.beginPath();ctx.arc(mx(player.position.x),mz(player.position.z),5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle='#174e42';ctx.beginPath();ctx.moveTo(mx(player.position.x),mz(player.position.z));ctx.lineTo(mx(player.position.x)-Math.sin(yaw)*12,mz(player.position.z)-Math.cos(yaw)*12);ctx.stroke();}
const cameraRay=new THREE.Raycaster();const cameraDirection=new THREE.Vector3();
const projection=new THREE.Vector3(),desired=new THREE.Vector3(),target=new THREE.Vector3();
function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);elapsed+=dt;world.update(elapsed,dt);let moving=false,running=false;
if(started&&!ui.opened){let side=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),forward=(keys.has('w')||keys.has('ArrowUp')?1:0)-(keys.has('s')||keys.has('ArrowDown')?1:0);side+=stick.axis.x;forward+=stick.axis.y;moving=Math.hypot(side,forward)>.08;running=keys.has('Shift');if(moving){if(celebrating)celebrating=false;const len=Math.hypot(side,forward),speed=running?6:4;side/=Math.max(1,len);forward/=Math.max(1,len);const dx=(Math.cos(yaw)*side-Math.sin(yaw)*forward)*dt*speed,dz=(-Math.sin(yaw)*side-Math.cos(yaw)*forward)*dt*speed;if(!isBlocked(player.position.x+dx,player.position.z))player.position.x+=dx;if(!isBlocked(player.position.x,player.position.z+dz))player.position.z+=dz;const angle=Math.atan2(dx,dz);let diff=THREE.MathUtils.euclideanModulo(angle-player.rotation.y+Math.PI,Math.PI*2)-Math.PI;player.rotation.y+=diff*Math.min(1,dt*12);if(elapsed-lastFoot>.42){sound('step');lastFoot=elapsed;}}
near=null;let nearest=2.5;for(const n of npcs){const distance=Math.hypot(n.model.position.x-player.position.x,n.model.position.z-player.position.z);if(distance<nearest){nearest=distance;near=n;}}$('#prompt').hidden=!near;$('#interact').hidden=!near;if(near)$('#prompt').textContent=`💬 Tekan E / BERCAKAP: ${near.mission.name}`;
if(elapsed-lastSave>2){save();lastSave=elapsed;}}
else{$('#prompt').hidden=true;$('#interact').hidden=true;}
animateCharacter(player,elapsed,moving,running,celebrating);for(const n of npcs){animateCharacter(n.model,elapsed+n.mission.x,false,false,celebrating);n.label.position.set(n.model.position.x,3.15+Math.sin(elapsed*2)*.09,n.model.position.z);n.label.el.classList.toggle('near',near===n&&!ui.opened);}
if(started){target.copy(player.position).add(new THREE.Vector3(0,1.4,0));if(talking)target.lerp(talking.model.position.clone().add(new THREE.Vector3(0,1.4,0)),.35);const radius=talking?8:11;desired.set(target.x+Math.sin(yaw)*radius,target.y+radius*Math.sin(pitch),target.z+Math.cos(yaw)*radius);cameraDirection.subVectors(desired,target).normalize();cameraRay.set(target,cameraDirection);const hit=cameraRay.intersectObjects(world.occluders,false)[0];if(hit&&hit.distance<target.distanceTo(desired))desired.copy(target).addScaledVector(cameraDirection,Math.max(1,hit.distance-.5));camera.position.lerp(desired,1-Math.exp(-dt*6));camera.lookAt(target);}else{camera.position.set(34,30,51);camera.lookAt(1,0,10);}
camera.updateMatrixWorld();for(const item of labelEntries){projection.copy(item.position).project(camera);const distance=camera.position.distanceTo(item.position);const visible=started&&projection.z<1&&projection.z>0&&distance<39;item.el.hidden=!visible;if(visible){item.el.style.left=(projection.x*.5+.5)*innerWidth+'px';item.el.style.top=(-projection.y*.5+.5)*innerHeight+'px';item.el.style.opacity=String(Math.min(1,(39-distance)/8));}}
renderer.render(scene,camera);if(started)drawMap();}
player.position.set(-24,0,6);frame();
// Runtime objects are exported for maintenance and automated interaction checks.
export {player,npcs,ui,isBlocked,interact,stick};
