export const missions=[
{id:'mei',name:'Mei Ling',place:'Pasar Raya',topic:'Perbelanjaan',x:24,z:4,shirt:0xef476f,skin:0xf0c7a0,longHair:true,question:'Hai! Saya hendak membeli hadiah untuk Hari Keluarga di taman kami. Saya mempunyai wang yang terhad. Apakah yang patut saya lakukan?',choices:['Membeli hadiah paling mahal supaya semua orang kagum.','Membeli hadiah yang sesuai dengan jumlah wang yang diperuntukkan.','Membeli banyak hadiah walaupun melebihi kemampuan.'],answer:1,explanation:'Kita perlu bersederhana dalam perbelanjaan dengan membeli barang mengikut kemampuan dan keperluan.',feelings:['😊 Gembira','😌 Tenang','🙏 Bersyukur']},
{id:'kumar',name:'Kumar',place:'Dewan Komuniti',topic:'Penampilan',x:0,z:4,shirt:0xffd166,skin:0x9c6848,question:'Kita akan menghadiri Majlis Hari Keluarga. Apakah pakaian yang paling sesuai?',choices:['Pakaian terlalu berlebihan dengan banyak aksesori.','Pakaian kemas, sopan dan sesuai dengan majlis.','Pakaian yang tidak sesuai dengan keadaan.'],answer:1,explanation:'Kesederhanaan dalam penampilan bermaksud berpakaian secara sopan, kemas dan sesuai dengan keadaan.',feelings:['😊 Selesa','😄 Gembira','👍 Yakin']},
{id:'teck',name:'Teck Seng',place:'Pusat Internet',topic:'Penggunaan Kemudahan',x:0,z:46,shirt:0x4ea8de,skin:0xe8bc93,question:'Saya suka bermain permainan komputer. Saya sudah menggunakan komputer ini agak lama. Apakah yang patut saya lakukan?',choices:['Terus bermain sepanjang hari.','Berhenti seketika dan memberi peluang kepada orang lain.','Menggunakan semua komputer yang ada.'],answer:1,explanation:'Kita perlu menggunakan kemudahan awam dengan sederhana dan memberi peluang kepada orang lain.',feelings:['😊 Gembira','🤝 Puas hati','❤️ Senang hati']},
{id:'aisyah',name:'Aisyah',place:'Rumah Terbuka',topic:'Pemakanan',x:0,z:25,shirt:0xb293db,skin:0xd6a475,longHair:true,question:'Banyak makanan disediakan untuk para tetamu. Apakah tindakan yang menunjukkan kesederhanaan?',choices:['Mengambil makanan sebanyak mungkin.','Mengambil makanan mengikut keperluan dan mengelakkan pembaziran.','Mengambil semua makanan kegemaran sebelum orang lain.'],answer:1,explanation:'Kesederhanaan dalam pemakanan bermaksud mengambil makanan secukupnya dan tidak membazir.',feelings:['🙏 Bersyukur','😊 Gembira','😌 Puas hati']},
{id:'ravi',name:'Ravi',place:'Taman Rekreasi',topic:'Perlakuan',x:0,z:-23,shirt:0x06b99b,skin:0xa36d4b,question:'Ramai penduduk sedang berehat di taman. Kawan kamu mahu bermain sambil menjerit dengan sangat kuat. Apakah tindakan kamu?',choices:['Menjerit lebih kuat.','Bermain dengan tertib dan menjaga suara supaya tidak mengganggu orang lain.','Menyuruh semua orang meninggalkan taman.'],answer:1,explanation:'Bersederhana dalam perlakuan bermaksud mengawal tingkah laku agar tidak mengganggu keselesaan orang lain.',feelings:['😊 Gembira','💗 Bangga','😌 Tenang']},
{id:'rahman',name:'Pak Cik Rahman',place:'Balai Komuniti',topic:'Pertuturan',x:-24,z:25,shirt:0xf4a261,skin:0xc38f68,hair:0x9a9990,adult:true,bonus:true,question:'Kamu bertemu jiran yang lebih tua. Bagaimanakah kamu patut bercakap dengannya?',choices:['Bercakap sesuka hati tanpa menjaga perasaan.','Bercakap dengan sopan dan menggunakan kata-kata yang sesuai.','Menjerit apabila bercakap.'],answer:1,explanation:'Bersederhana dalam pertuturan membantu kita menjaga perasaan orang lain dan mewujudkan hubungan masyarakat yang harmoni.',feelings:['😊 Gembira','😌 Tenang','❤️ Senang hati']}
];
export const KEY='harmoni-3d-v1';
export const fresh=()=>({version:1,name:'',done:{},attempts:{},feelings:{},reflection:{ways:[],feeling:'',pledges:[]},sound:false,position:{x:-24,z:6},finished:false});
export function readState(){try{const s=JSON.parse(localStorage.getItem(KEY));if(!s||s.version!==1||typeof s.name!=='string')return null;const n=fresh();n.name=s.name.slice(0,40);n.sound=s.sound===true;for(const m of missions){n.attempts[m.id]=Math.max(0,Number(s.attempts?.[m.id])||0);if(s.done?.[m.id]===10||s.done?.[m.id]===20||(m.bonus&&s.done?.[m.id]===0))n.done[m.id]=s.done[m.id];if(typeof s.feelings?.[m.id]==='string')n.feelings[m.id]=s.feelings[m.id];}if(s.reflection&&Array.isArray(s.reflection.ways)&&Array.isArray(s.reflection.pledges)){n.reflection.ways=s.reflection.ways.filter(x=>Number.isInteger(x)&&x>=0&&x<5);n.reflection.pledges=s.reflection.pledges.filter(x=>Number.isInteger(x)&&x>=0&&x<6);n.reflection.feeling=typeof s.reflection.feeling==='string'?s.reflection.feeling:'';}n.finished=s.finished===true&&completed(n)===5&&n.reflection.ways.length>=3&&!!n.reflection.feeling&&n.reflection.pledges.length>0;if(Number.isFinite(s.position?.x)&&Number.isFinite(s.position?.z)&&Math.abs(s.position.x)<38&&s.position.z>-37&&s.position.z<57)n.position=s.position;return n;}catch{return null;}}
export function completed(s){return missions.filter(m=>!m.bonus&&Object.hasOwn(s.done,m.id)).length;}
export function score(s){return missions.filter(m=>!m.bonus).reduce((n,m)=>n+(s.done[m.id]||0),0);}
export function saveState(s){try{localStorage.setItem(KEY,JSON.stringify(s));return true;}catch{return false;}}
